# Configuration for weekly-digest - https://github.com/apps/weekly-digest
publishDay: fri
canPublishIssues: true
canPublishPullRequests: false
canPublishContributors: false
canPublishStargazers: false
canPublishCommits: true
